### ISSUE TITLE
Add projetos da disciplina ao README

### ISSUE THREAD

**Issue by diogosm** [diogosm/android_class_IArTES#1]
Task: add repo dos projetos desenvolvidos no módulo de android

**Comment by gabrielclavila** [comment]
https://github.com/gabrielclavila/ProjetoAndroidIARTES

**Comment by NoraneyseT** [comment]
https://github.com/thiagos98/SafeCampus

**Comment by brunaMF** [comment]
https://github.com/deboradcm/ConexaoCursosAPP

**Comment by emily-nicole-aguiar** [comment]
https://github.com/emily-nicole-aguiar/AppDespesas

**Comment by jessikaaguido** [comment]
https://github.com/jessikaaguido/RENTENV/tree/main/assets

**Comment by jessikaaguido** [comment]
https://github.com/jessikaaguido/RENTENV

**Comment by chmilena** [comment]
https://github.com/chmilena/APP_Senior_Health

**Comment by priscilafraser** [comment]
https://github.com/AnaCristina1972/Pagela

**Comment by Yeninr** [comment]
https://github.com/Yeninr/7030Finance/tree/master.
